name: Angular CI/CD (With Docker Runtime Env)

on:
  push:
    branches:
      - development

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # ✅ Шаг 1: Клонирование репозитория
      - name: Checkout Repo
        uses: actions/checkout@v3

      # ✅ Шаг 2: Сборка Docker-образа
      - name: Build Docker Image
        run: docker build -t my-angular-app .

      # ✅ Шаг 3: Остановка старого контейнера и запуск нового с переменными
      - name: Run Docker Container
        run: |
          # Остановка и удаление старого контейнера, если он существует
          docker stop my-angular-app || true
          docker rm my-angular-app || true

          # Запуск нового контейнера с переменными окружения
          docker run -d -p 4200:80 --env API_AUTH_URL=${{ secrets.API_AUTH_URL }} API_MATCHMAKING_URL=${{ secrets.API_MATCHMAKING_URL }} --name my-angular-app my-angular-app:latest
